# /etc/nginx/nginx.conf:

http {
        ## GZIP (fallback compression)
        gzip on;
        gzip_comp_level 6;
        gzip_min_length 1000;
        gzip_vary on;
        gzip_types
            text/plain
            text/css
            application/json
            application/javascript
            application/xml
            application/rss+xml
            image/svg+xml;

        ## BROTLI (IF MODULE IS INSTALLED, may require additional libnginx-mod-http-brotli-filter):
        brotli on;
        brotli_comp_level 5;
        # brotli_static on; # <- Only for serving pre-compressed .br files (may require additional module libnginx-mod-http-brotli-static)
        brotli_types
            text/plain
            text/css
            application/javascript
            application/json
            image/svg+xml;

        ## FILE CACHE (very important for static sites):
        open_file_cache max=10000 inactive=60s;
        open_file_cache_valid 120s;
        open_file_cache_min_uses 2;
        open_file_cache_errors on;
       
        server {
            ## SECURITY:
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header Referrer-Policy "strict-origin-when-cross-origin" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        }
}

## /etc/nginx/sites-available/my-site.com:

server {
    listen 443 ssl http2;      # ENABLE HTTP2
    listen [::]:443 ssl http2; # ENABLE HTTP2
   
    # DO NOT CACHE HTML:
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
   
    # LONG CACHE IMMUTABLE ASSETS:
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
